name: depoly

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16.16.0
    if: "contains(github.event.head_commit.message, 'cicd:')"
    steps:
    - uses: actions/checkout@v3

    - name: set nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: install
      run: npm i -f

    - name: build
      run: npm run build

    - name: Upload Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: dist
        retention-days: 1 # <= 这里可以设置保留天数1

  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [build] # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    container: node:16.16.0
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
      uses: actions/download-artifact@v3
      with:
        name: site
        path: dist
        
    - name: Install rsync 📚
      run: |
        apt-get update && apt-get install -y rsync

    - uses: JamesIves/github-pages-deploy-action@4.4.2
      with:
        token: ${{ secrets.CDAPK }}
        folder: dist
        repository-name: laof/e
        branch: main
        clean: true
        force: true
        commit-message: release by action
