name: depoly


on: push

jobs:
  build:
    name: deploy files info
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'cicd:')"
    steps:
      - uses: actions/checkout@v3

      - name: set nodejs
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
      - run: npm i -f

      - name: build
      - run: npm run build --prod

      - name: Upload Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: build

  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [build] # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
      uses: actions/download-artifact@v3
      with:
        name: site
        path: build

    - uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        token: ${{ secrets.CDAPK }}
        folder: build
        repository-name: laof/a
        target-folder: ./
        branch: main
        clean: false
        force: false
        commit-message: release by action